import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import pdfParse from 'pdf-parse';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const dataDir = path.join(root, 'data');
const sourceDir = path.join(root, 'Source');

async function readJson(filePath) {
  const raw = await fs.readFile(filePath, 'utf8');
  return JSON.parse(raw);
}

function splitPdfTextToParagraphs(text) {
  return text
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .map((p) => p.replace(/\s+/g, ' ').trim())
    .filter((p) => p.length > 40);
}

function paragraphsToBlocks(paragraphs) {
  return paragraphs.map((text, index) => ({
    type: 'paragraph',
    ...(index === 0 ? { lead: true } : {}),
    text,
  }));
}

async function extractBlocksFromPdf(pdfPath) {
  const buffer = await fs.readFile(pdfPath);
  const result = await pdfParse(buffer);
  const paragraphs = splitPdfTextToParagraphs(result.text);
  if (paragraphs.length === 0) {
    throw new Error(
      'No text extracted from PDF. Add "blocks" in data/article.json or use a text-based PDF.',
    );
  }
  return paragraphsToBlocks(paragraphs);
}

async function main() {
  const article = await readJson(path.join(dataDir, 'article.json'));
  const { sourcePdf, blocks: jsonBlocks, contentSource: mode = 'json' } = article;

  let contentBlocks = [];
  let contentSource = '';

  if (sourcePdf) {
    const pdfPath = path.join(sourceDir, sourcePdf);
    const pdfExists = await fs.access(pdfPath).then(() => true).catch(() => false);

    if (!pdfExists) {
      throw new Error(`Missing PDF: Source/${sourcePdf} — add the file and commit it to the repo.`);
    }

    if (mode === 'pdf' || !jsonBlocks?.length) {
      contentBlocks = await extractBlocksFromPdf(pdfPath);
      contentSource = `extracted from Source/${sourcePdf}`;
    } else {
      contentBlocks = jsonBlocks;
      contentSource = `from data/article.json (PDF: Source/${sourcePdf})`;
    }
  } else if (jsonBlocks?.length) {
    contentBlocks = jsonBlocks;
    contentSource = 'from data/article.json';
  } else {
    throw new Error('Set sourcePdf in data/article.json and add the PDF under Source/, or define blocks.');
  }

  const content = {
    generatedAt: new Date().toISOString(),
    sourcePdf: sourcePdf ?? null,
    source: contentSource,
    blocks: contentBlocks,
  };

  await fs.writeFile(
    path.join(dataDir, 'content.json'),
    JSON.stringify(content, null, 2),
    'utf8',
  );

  const site = await readJson(path.join(dataDir, 'site.json'));
  const bundleJs = `/* Generated by npm run build */\nwindow.__ARTICLE_DATA__ = ${JSON.stringify({ article, content, site })};\n`;

  await fs.mkdir(path.join(root, 'js'), { recursive: true });
  await fs.writeFile(path.join(root, 'js', 'data-bundle.js'), bundleJs, 'utf8');

  console.log(`Build OK: ${contentBlocks.length} blocks — ${contentSource}`);
  console.log('Output: data/content.json, js/data-bundle.js');
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
