import fs from 'fs/promises';
import { createWriteStream } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import pdfParse from 'pdf-parse';
import PDFDocument from 'pdfkit';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const dataDir = path.join(root, 'data');
const sourceDir = path.join(root, 'Source');

async function readJson(filePath) {
  const raw = await fs.readFile(filePath, 'utf8');
  return JSON.parse(raw);
}

function splitPdfTextToParagraphs(text) {
  return text
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .map((p) => p.replace(/\s+/g, ' ').trim())
    .filter((p) => p.length > 40);
}

function paragraphsToBlocks(paragraphs) {
  return paragraphs.map((text, index) => ({
    type: 'paragraph',
    ...(index === 0 ? { lead: true } : {}),
    text,
  }));
}

async function ensureSamplePdf(filename, blocks) {
  const pdfPath = path.join(sourceDir, filename);
  try {
    await fs.access(pdfPath);
    return;
  } catch {
    /* create sample */
  }

  await fs.mkdir(sourceDir, { recursive: true });

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 72 });
    const writeStream = createWriteStream(pdfPath);
    doc.pipe(writeStream);

    doc.fontSize(22).text('The Quiet Case for Slowing Down');
    doc.moveDown();
    doc.fontSize(12);

    for (const block of blocks) {
      if (block.type === 'heading') {
        doc.moveDown();
        doc.fontSize(14).text(block.text);
        doc.fontSize(12);
      } else if (block.type === 'quote') {
        doc.moveDown();
        doc.font('Helvetica-Oblique').text(`"${block.text}"`, { indent: 24 });
        if (block.cite) doc.text(`— ${block.cite}`, { indent: 24 });
        doc.font('Helvetica');
      } else if (block.type === 'paragraph' || block.type === 'closing') {
        doc.moveDown(0.5);
        doc.text(block.text, { align: 'justify' });
      }
    }

    doc.end();
    writeStream.on('finish', resolve);
    writeStream.on('error', reject);
  });

  console.log(`Created sample PDF: Source/${filename}`);
}

async function extractBlocksFromPdf(pdfPath) {
  const buffer = await fs.readFile(pdfPath);
  const result = await pdfParse(buffer);
  const paragraphs = splitPdfTextToParagraphs(result.text);
  if (paragraphs.length === 0) {
    throw new Error('No text extracted from PDF. Add structured blocks in data/article.json.');
  }
  return paragraphsToBlocks(paragraphs);
}

async function main() {
  const articlePath = path.join(dataDir, 'article.json');
  const article = await readJson(articlePath);
  const { sourcePdf, blocks: jsonBlocks, contentSource: mode = 'json' } = article;

  let contentBlocks = [];
  let contentSource = '';

  if (sourcePdf) {
    await fs.mkdir(sourceDir, { recursive: true });
    const pdfPath = path.join(sourceDir, sourcePdf);
    let pdfExists = await fs.access(pdfPath).then(() => true).catch(() => false);

    if (!pdfExists && jsonBlocks?.length) {
      await ensureSamplePdf(sourcePdf, jsonBlocks);
      pdfExists = true;
    }

    if (!pdfExists) {
      throw new Error(
        `PDF not found: Source/${sourcePdf}. Place your file there or run build after adding blocks.`,
      );
    }

    if (mode === 'pdf') {
      contentBlocks = await extractBlocksFromPdf(pdfPath);
      contentSource = `extracted from Source/${sourcePdf}`;
    } else if (jsonBlocks?.length) {
      contentBlocks = jsonBlocks;
      contentSource = `from data/article.json blocks (PDF: Source/${sourcePdf})`;
    } else {
      contentBlocks = await extractBlocksFromPdf(pdfPath);
      contentSource = `extracted from Source/${sourcePdf} (no blocks in JSON)`;
    }
  } else if (jsonBlocks?.length) {
    contentBlocks = jsonBlocks;
    contentSource = 'from data/article.json blocks';
  } else {
    throw new Error('Define sourcePdf and/or blocks in data/article.json.');
  }

  const content = {
    generatedAt: new Date().toISOString(),
    sourcePdf: sourcePdf ?? null,
    source: contentSource,
    blocks: contentBlocks,
  };

  await fs.writeFile(
    path.join(dataDir, 'content.json'),
    JSON.stringify(content, null, 2),
    'utf8',
  );

  const site = await readJson(path.join(dataDir, 'site.json'));
  const bundle = { article, content, site };
  const bundleJs = `/* Generated by npm run build — do not edit */\nwindow.__ARTICLE_DATA__ = ${JSON.stringify(bundle)};\n`;

  await fs.mkdir(path.join(root, 'js'), { recursive: true });
  await fs.writeFile(path.join(root, 'js', 'data-bundle.js'), bundleJs, 'utf8');

  console.log(`Wrote data/content.json (${contentBlocks.length} blocks) — ${contentSource}`);
  console.log('Wrote js/data-bundle.js (for browser — works without a server)');
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
